version: '2'

services:
  sdsb4d-backend:
    container_name: sdsb4d-backend
    image: sdsb4d-backend:0.0.1
    build: .
    volumes:
    - ./backend:/app/backend
    ports:
      - 9091:9091
    restart: always